In [1]:
import pandas as pd
data = pd.read_csv("wiki_movie_plots_deduped.csv")
data.head()

,Release Year,Title,Origin/Ethnicity,Director,Cast,Genre,Wiki Page,Plot
0,1901,Kansas Saloon Smashers,American,Unknown,NaN,unknown,https://en.wikipedia.org/wiki/Kansas_Saloon_Sm...,"A bartender is working at a saloon, serving dr..."
1,1901,Love by the Light of the Moon,American,Unknown,NaN,unknown,https://en.wikipedia.org/wiki/Love_by_the_Ligh...,"The moon, painted with a smiling face hangs ov..."
2,1901,The Martyred Presidents,American,Unknown,NaN,unknown,https://en.wikipedia.org/wiki/The_Martyred_Pre...,"The film, just over a minute long, is composed..."
3,1901,"Terrible Teddy, the Grizzly King",American,Unknown,NaN,unknown,"https://en.wikipedia.org/wiki/Terrible_Teddy,_...",Lasting just 61 seconds and consisting of two ...
4,1902,Jack and the Beanstalk,American,"George S. Fleming, Edwin S. Porter",NaN,unknown,https://en.wikipedia.org/wiki/Jack_and_the_Bea...,The earliest known adaptation of the classic f...

In [2]:
data.shape

(34886, 8)

In [3]:
import numpy as np
np.unique(data['Origin/Ethnicity'])

array(['American', 'Assamese', 'Australian', 'Bangladeshi', 'Bengali',
       'Bollywood', 'British', 'Canadian', 'Chinese', 'Egyptian',
       'Filipino', 'Hong Kong', 'Japanese', 'Kannada', 'Malayalam',
       'Malaysian', 'Maldivian', 'Marathi', 'Punjabi', 'Russian',
       'South_Korean', 'Tamil', 'Telugu', 'Turkish'], dtype=object)

In [4]:
data2 = data.loc[(data['Origin/Ethnicity']=='American') & (data['Release Year']>2015)]
len(data2)

350

In [5]:
my_data = pd.DataFrame(data2)

In [6]:
my_data.tail()

,Release Year,Title,Origin/Ethnicity,Director,Cast,Genre,Wiki Page,Plot
17372,2017,Crooked House,American,Gilles Paquet-Brenner,Gilles Paquet-Brenner (director/screenplay); T...,"crime, drama, mystery",https://en.wikipedia.org/wiki/Crooked_House_(f...,The granddaughter of late business tycoon Aris...
17373,2017,Hostiles,American,Scott Cooper,Scott Cooper (director/screenplay); Donald E. ...,western,https://en.wikipedia.org/wiki/Hostiles_(film),"In 1892, settler Wesley Quaid and his family a..."
17374,2017,All the Money in the World,American,Ridley Scott,Ridley Scott (director); David Scarpa (screenp...,"biography, crime, drama",https://en.wikipedia.org/wiki/All_the_Money_in...,"In 1973, 16-year-old John Paul Getty III (Paul..."
17375,2017,Molly's Game,American,Aaron Sorkin,Aaron Sorkin (director/screenplay); Jessica Ch...,"biography, crime, drama",https://en.wikipedia.org/wiki/Molly%27s_Game,Molly Bloom is world-class mogul skier with Ol...
17376,2017,Phantom Thread,American,Paul Thomas Anderson,Paul Thomas Anderson (director/screenplay); Da...,drama,https://en.wikipedia.org/wiki/Phantom_Thread,"In 1954 London, renowned fashion designer Reyn..."

In [7]:
finaldata = my_data[["Title", "Plot"]]          
finaldata = finaldata.set_index('Title')    
  
finaldata.head(50)

                                                                                        Plot
Title
The Forest                                 The majority of the story is set in and around...
Anesthesia                                 Philosophy professor Walter Zarrow is wounded ...
Lamb                                       The film opens with David Lamb (Ross Partridge...
Ride Along 2                               The film starts in Miami on the boat of crime ...
13 Hours: The Secret Soldiers of Benghazi  In 2012, Benghazi, Libya is named one of the m...
Norm of the North                          Norm the polar bear is the son of the king of ...
Dirty Grandpa                              Jason Kelly is a lawyer who works for his fath...
The 5th Wave                               Ohio high-schooler Cassie Sullivan, armed with...
The Boy                                    Greta Evans, a young American from Montana, is...
Ip Man 3                                   In 1959, Ip Man is settling into his low-profi...
Synchronicity                              Physicist Jim Beale, working with two colleagu...
Kung Fu Panda 3                            In the spirit realm, Oogway fights against an ...
The Finest Hours                           Bernard "Bernie" Webber, a crewman at the Coas...
Jane Got a Gun                             Jane and her husband Bill "Ham" Hammond live i...
Hail, Caesar!                              In 1951, Eddie Mannix (Josh Brolin) is the hea...
Pride + Prejudice + Zombies                Early 19th century England is beset by zombies...
The Choice                                 Travis Shaw (Benjamin Walker) is a veterinaria...
Deadpool                                   Wade Wilson is a dishonorably discharged speci...
Zoolander 2                                At Fashion Interpol, Valentina Valencia examin...
How to Be Single                           Alice (Dakota Johnson) temporarily dumps her c...
Risen                                      After crushing a Zealot revolt led by Barabbas...
The Witch                                  In 1630s New England, a man named William is b...
Race                                       Jesse Owens, a promising black American runner...
Gods of Egypt                              In an alternate version of Egypt, the world is...
Triple 9                                   In Atlanta, Georgia, criminals Michael Atwood ...
Zootopia                                   In a world populated by anthropomorphic mammal...
London Has Fallen                          Western intelligence services of the G8 track ...
Whiskey Tango Foxtrot                      In 2003 New York City, dissatisfied with the s...
The Other Side of the Door                 Sets in the 19th century, the plot centered on...
10 Cloverfield Lane                        After breaking up with her boyfriend Ben, Mich...
The Young Messiah                          At the age of 7, when Jesus returns from Egypt...
The Perfect Match                          Charlie is a playboy who's convinced that rela...
Hello, My Name Is Doris                    Doris Miller is a shy, eccentric 60-something ...
Miracles from Heaven                       Set in Burleson, Texas, between 2008 and 2012,...
The Divergent Series: Allegiant            After Evelyn forbids anyone from leaving Chica...
The Bronze                                 Former gymnastics Bronze Medalist Hope Ann Gre...
Midnight Special                           In a motel, Roy Tomlin and his friend Lucas wa...
Batman v Superman: Dawn of Justice         Eighteen months after the battle between Super...
My Big Fat Greek Wedding 2                 Toula Portokalos-Miller's (Nia Vardalos) life ...
Everybody Wants Some!!                     In Texas in the fall of 1980, college freshman...
God's Not Dead 2                           AP History teacher Grace Wesley (Melissa Joan ...
Meet the Blacks                            Carl Black and his family are getting out of C...
Miles Ahead                                Adapted from Sony Classics[5]\r\nIn the midst ...
The Boss                                   The story follows Michelle Darnell (Melissa Mc...
Hardcore Henry                             Waking inside a laboratory on an airship, a ma...
Demolition                                 Davis is a successful investment banker at a f...
The Invitation                             Will drives with his new girlfriend Kira to th...
The Jungle Book                            Mowgli is a "man cub" raised by the wolf Raksh...
Barbershop: The Next Cut                   To survive harsh economic times, Calvin has me...
Criminal                                   When Spanish industrialist-turned-anarchist Xa...

In [8]:
finaldata["Plot"]["Criminal"]

'When Spanish industrialist-turned-anarchist Xavier Heimdahl arranges for his associate Jan Strook—a hacker known as "the Dutchman"—to create a wormhole program that would allow the owner to bypass all computer codes protecting the world\'s nuclear defense codes, the Dutchman panics and attempts to hand his secret over to the CIA. He makes contact with London-based agent Bill Pope, but although Pope is able to get the Dutchman to a safe house and recover the money to pay him for his services, he is caught by Heimdahl\'s men and tortured to death before he can tell anyone where he hid the Dutchman.\r\nDesperate to find the Dutchman, Pope\'s CIA supervisor Quaker Wells contacts Dr. Micah Franks, who has developed a treatment that could theoretically plant the memory patterns of a dead man onto a living one. Keeping Pope\'s brain stimulated to preserve its knowledge, Franks requests that convict Jerico Stewart be the subject of the procedure, as Stewart\'s criminal behavior is the result of childhood brain trauma leaving him with an underdeveloped frontal lobe, hindering his emotional development and impulse control, that they can use to "graft" Pope\'s knowledge into Stewart\'s mind.\r\nWhile the process initially appears unsuccessful, Jerico is able to escape custody while being transferred after the operation, faking his death and heading to Pope\'s house, where he ties Pope\'s wife, Jillian, to her bed and gags her mouth with duct tape, is able to disable the house alarms and delay an investigation of the silent alarm which Jillian manages to activate. As time goes on, he experiences memory flashes of Pope\'s past, but all he can determine is that the bag of money was hidden behind a shelf of books relating to George Orwell, without identifying where it or the Dutchman are kept.\r\nThe CIA becomes increasingly anxious to find the Dutchman when they learn that he is now planning to sell the program to the Russians, believing that the CIA has betrayed him. Fortunately, they are able to find Jerico after he contacts Dr. Franks for medication using Pope\'s CIA codes, Franks\'s questioning confirming that Jerico is developing emotions as well as drawing on Pope\'s experience. As Jerico attempts to retrace the route Pope took to hide the Dutchman, Heimdahl creates a distraction at the airport that draws Quaker\'s attention, allowing Heimdahl\'s henchwoman Elsa to try and capture Jerico, killing his CIA guards before Jerico escapes by driving off a bridge.\r\nHis leg injured in his escape, Jerico retreats to the Pope house, where he encounters Jillian and explains the situation to her. Although initially concerned, Jillian comes to accept Jerico\'s story as she sees him interacting with her daughter, Emma, allowing Jerico to stay the night. Jerico forms a bond with the two. The next morning, Jerico realizes through a conversation with Jillian that the bag is hidden in the rare books collection at the University of London where she works. He attempts to retrieve the bag, but he is captured by Heimdahl and Elsa once he has found it. Heimdahl forces him to take them to the Dutchman or he will kill Jillian and Emma.\r\nWith the CIA and a Russian strike team now seeking the Dutchman, Jerico—who has recalled that Pope hid the Dutchman in Jillian\'s office at the university—is able to escape Elsa using an improvised nitro-glycerine bomb, returning to the office to provide a hurried explanation to the Dutchman. The two are caught by Elsa before they can escape, Jerico is shot in the shoulder and after she kills the Dutchman, Jerico knocks her out with a potted cactus before killing her by bashing her head in with a lamp.\r\nTaking the flash drive containing the wormhole program to the airfield where Heimdahl is attempting an escape, Jerico is able to save Jillian and Emma despite Quaker\'s protests about the danger Heimdahl could pose with the program. As Heimdahl\'s plane takes off, Jerico reveals to Quaker that he had the Dutchman reprogram the wormhole so that it would target the source of the next transmission, resulting in Heimdahl unwittingly destroying his own plane when he tries to fire a missile at the airfield.\r\nA few months later, Jerico is shown on the beach where Pope and Jillian had their honeymoon, initially unresponsive to anything but automatic reflexes and responses. With all other options exhausted, Quaker and Franks take Jillian and Emma to see him, the sight of Pope\'s family confirming that some part of Pope exists in Jerico when he responds with a nose-tap that was Pope and Jillian\'s way of saying "I love you" in private. Witnessing this, Quaker reflects that he will offer Jerico a job.'

In [9]:
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')
nltk.download('stopwords')

from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [10]:
def preprocess_sentences(text):
    text = text.lower()
    words = nltk.word_tokenize(text)
    my_sent=[lemmatizer.lemmatize(word) for word in words if word not in stopwords.words('english')]
    finalsent = ' '.join(my_sent)

    finalsent = finalsent.replace("n't", " not")
    finalsent = finalsent.replace("'m", " am")
    finalsent = finalsent.replace("'s", " is")
    finalsent = finalsent.replace("'re", " are")
    finalsent = finalsent.replace("'ll", " will")
    finalsent = finalsent.replace("'ve", " have")
    finalsent = finalsent.replace("'d", " would")
    
    return finalsent

finaldata["new_plot"]= finaldata["Plot"].apply(preprocess_sentences)
finaldata.head()

,Plot,new_plot
Title,,
The Forest,The majority of the story is set in and around...,"majority story set around aokigahara forest , ..."
Anesthesia,Philosophy professor Walter Zarrow is wounded ...,philosophy professor walter zarrow wounded mug...
Lamb,The film opens with David Lamb (Ross Partridge...,film open david lamb ( ross partridge ) visiti...
Ride Along 2,The film starts in Miami on the boat of crime ...,film start miami boat crime lord antonio pope ...
13 Hours: The Secret Soldiers of Benghazi,"In 2012, Benghazi, Libya is named one of the m...","2012 , benghazi , libya named one dangerous pl..."

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer
  
tfidf = TfidfVectorizer()
tfidf_movieid = tfidf.fit_transform((finaldata["new_plot"]))

# Finding cosine similarity between vectors
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(tfidf_movieid, tfidf_movieid)

In [12]:
indices = pd.Series(finaldata.index)
def recommendations(title, cosine_sim = similarity):
  try:
    index = indices[indices == title].index[0]
    print(index)
    similarity_scores = pd.Series(cosine_sim[index]).sort_values(ascending = False)
    print(similarity_scores)
    top_10_movies = list(similarity_scores.iloc[1:11].index)
    print(top_10_movies)
    recommended_movies = [list(finaldata.index)[i] for i in top_10_movies]
    return recommended_movies
  except:
    print("No movie name found")

In [13]:
recommendations("Harry Potter and the Chamber of Secrets")

No movie name found

In [14]:
recommendations("Spider-Man")

No movie name found

In [18]:
recommendations("Lamb")

2
2      1.000000
116    0.281415
98     0.260506
46     0.258326
214    0.206589
         ...
200    0.000000
268    0.000000
261    0.000000
259    0.000000
28     0.000000
Length: 350, dtype: float64
[116, 98, 46, 214, 92, 34, 40, 201, 19, 137]

['Masterminds',
 'War Dogs',
 'The Invitation',
 'Alien: Covenant',
 'Nine Lives',
 'The Divergent Series: Allegiant',
 "God's Not Dead 2",
 'Unforgettable',
 'How to Be Single',
 'Underworld: Blood Wars']